### ISSUE TITLE
Add CONTRIBUTION.md file 

### ISSUE THREAD

**Issue by Abhineshhh** [Arbtrage/Enigma#5]
**Is your feature request related to a problem? Please describe.**
CONTRIBUTION.md file  missing..
**Describe the solution you'd like**
i wanna make a CONTRIBUTION.md file for this repo

**Comment by Abhineshhh** [comment]
Can u assign me with this issue under SWOC'24

**Comment by Arbtrage** [comment]
Hey @AbhineshJha , there is already a contribution.md file in the docs directory . 
https://github.com/Arbtrage/Enigma/blob/main/docs/CONTRIBUTING.md

**Comment by Abhineshhh** [comment]
oohk sir , sorry for inconvenience !
